// Every topic from AboutMe.md lives here as data. The UI is generic and reads this file.
// To change a module, edit its fields, KPIs or starter items below.

const text = (key, label, o = {}) => ({ key, label, type: 'text', ...o });
const area = (key, label, o = {}) => ({ key, label, type: 'textarea', ...o });
const num = (key, label, o = {}) => ({ key, label, type: 'number', ...o });
const sel = (key, label, options, o = {}) => ({ key, label, type: 'select', options, ...o });
const date = (key = 'date', label = 'Date', o = {}) => ({ key, label, type: 'date', default: 'today', ...o });
const url = (key, label, o = {}) => ({ key, label, type: 'url', ...o });
const check = (key, label, o = {}) => ({ key, label, type: 'check', ...o });
const time = (key, label, o = {}) => ({ key, label, type: 'time', ...o });

const AREAS = ['GenAI internship', 'Making money', 'Academics', 'Fitness and health', 'Other'];
const OPEN_STAGES = ['Lead', 'Contacted', 'Replied', 'Call booked', 'Proposal'];
const inr = (n) => '₹' + Number(n || 0).toLocaleString('en-IN');

export const GROUPS = [
  { id: 'direction', name: 'Direction', slugs: ['profile', 'priorities', 'targets', 'roadmap'] },
  { id: 'study', name: 'Study', slugs: ['academics', 'gate', 'dsa', 'skills'] },
  { id: 'career', name: 'Career', slugs: ['projects', 'internships', 'hackathons'] },
  { id: 'money', name: 'Money', slugs: ['money', 'clients', 'ugc', 'products', 'ideas', 'investing'] },
  { id: 'body', name: 'Body and mind', slugs: ['fitness', 'nutrition', 'appearance', 'sleep', 'screen', 'chess'] },
  { id: 'daily', name: 'Daily and reach', slugs: ['planner', 'social'] },
];

export const HOOKS = {
  sleep(d) {
    if (d.bed && d.wake) {
      const [bh, bm] = d.bed.split(':').map(Number);
      const [wh, wm] = d.wake.split(':').map(Number);
      let mins = wh * 60 + wm - (bh * 60 + bm);
      if (mins <= 0) mins += 1440;
      d.hours = Math.round(mins / 6) / 10;
      d.earlyBed = bh >= 18;
      d.earlyWake = wh >= 3 && wh * 60 + wm <= 390;
    }
    return d;
  },
};

export const MODULES = [
  // ───────────────────────── Direction
  {
    slug: 'profile',
    name: 'Profile and principles',
    icon: 'profile',
    blurb: 'Who you are, and the rules you keep coming back to.',
    summary:
      'A second year Computer Engineering student in Pune turning into a highly capable AI and GenAI engineer with strong income potential, while building fitness, discipline, entrepreneurial ability and financial independence.',
    facts: [
      ['Name', 'Tanmay Anant Bulbule'],
      ['Age', '@age'],
      ['Born', '3 March 2008'],
      ['Location', 'Pune, Maharashtra'],
      ['Role', 'Student'],
      ['Chain', 'Skills, projects, internship, money, leverage'],
    ],
    entity: 'entry',
    fields: [
      text('title', 'Title', { required: true }),
      sel('kind', 'Type', ['Principle', 'Rule', 'Reminder', 'Reflection']),
      area('note', 'Note'),
    ],
    titleKey: 'title',
    subKey: 'note',
    filterKey: 'kind',
    chips: ['kind'],
    kpis: [{ label: 'Principles', calc: 'count', where: { kind: 'Principle' } }],
    seeds: [
      { kind: 'Principle', title: 'Choose fewer targets and finish them', note: 'The constraint is not information. It is execution density: starting too many things and finishing too few.' },
      { kind: 'Principle', title: 'Skills, projects, internship, money, leverage', note: 'Do not depend on the college brand. Let skills, portfolio, projects, network and results create the opportunities.' },
      { kind: 'Principle', title: 'Real projects over certificates', note: 'Build things that solve real problems, not projects that only demonstrate a technology.' },
      { kind: 'Principle', title: 'Evidence over hype', note: 'Systems over vague motivation. Test what actually converts before believing the advice.' },
      { kind: 'Principle', title: 'Become difficult to ignore', note: 'Build, solve, sell, communicate, learn quickly, use AI well, make money and create leverage.' },
      { kind: 'Rule', title: 'No new idea until the current one ships', note: 'Write new ideas in the Ideas module and keep going.' },
    ],
  },
  {
    slug: 'priorities',
    name: 'Priorities',
    icon: 'priorities',
    blurb: 'The weights you chose, next to where your hours really went.',
    facts: [
      ['GenAI internship', '40%'],
      ['Making money', '30%'],
      ['Academics, 8+ SGPA', '20%'],
      ['Fitness, health, cognition', '10%'],
    ],
    entity: 'entry',
    extra: 'priorities',
    fields: [
      sel('kind', 'Type', ['Weight', 'Hours']),
      sel('area', 'Area', AREAS),
      num('weight', 'Weight', { unit: '%', showWhen: { kind: 'Weight' }, required: true }),
      num('hours', 'Hours', { unit: 'h', showWhen: { kind: 'Hours' }, required: true }),
      date('date', 'Date', { showWhen: { kind: 'Hours' } }),
      text('note', 'Note'),
    ],
    titleFn: (d) => (d.kind === 'Weight' ? `${d.area} weight` : `${d.area} time`),
    subKey: 'note',
    filterKey: 'kind',
    chips: ['weight', 'hours', 'date'],
    kpis: [
      { label: 'Weights total', calc: 'sum', key: 'weight', where: { kind: 'Weight' }, unit: '%', target: 100 },
      { label: 'Hours logged, 7 days', calc: 'sum', key: 'hours', where: { kind: 'Hours' }, period: '7d', unit: 'h' },
    ],
    seeds: [
      { kind: 'Weight', area: 'GenAI internship', weight: 40 },
      { kind: 'Weight', area: 'Making money', weight: 30 },
      { kind: 'Weight', area: 'Academics', weight: 20 },
      { kind: 'Weight', area: 'Fitness and health', weight: 10 },
    ],
  },
  {
    slug: 'targets',
    name: '90 day targets',
    icon: 'targets',
    blurb: 'The three month direction, with numbers you can move.',
    facts: [
      ['Window', 'Next 3 months'],
      ['Rule', 'Every target needs a number'],
    ],
    entity: 'target',
    fields: [
      text('title', 'Target', { required: true }),
      sel('area', 'Area', AREAS),
      num('current', 'Current'),
      num('target', 'Goal', { required: true }),
      text('unit', 'Unit', { placeholder: 'questions, offers, rupees' }),
      date('deadline', 'Deadline', { default: '' }),
      sel('status', 'Status', ['Not started', 'In progress', 'Done', 'Dropped']),
    ],
    titleKey: 'title',
    statusKey: 'status',
    progress: { cur: 'current', tgt: 'target', unitKey: 'unit' },
    filterKey: 'status',
    chips: ['area', 'deadline'],
    kpis: [
      { label: 'Targets', calc: 'count' },
      { label: 'Done', calc: 'count', where: { status: 'Done' } },
    ],
    seeds: [
      { title: 'Get a paid GenAI internship', area: 'GenAI internship', current: 0, target: 1, unit: 'offer', status: 'In progress' },
      { title: 'Ship serious portfolio projects', area: 'GenAI internship', current: 0, target: 2, unit: 'shipped', status: 'In progress' },
      { title: 'Earn ₹6k to ₹10k+ per month', area: 'Making money', current: 0, target: 6000, unit: '₹ per month', status: 'In progress' },
      { title: 'Solve 150+ DSA questions', area: 'Academics', current: 0, target: 150, unit: 'questions', status: 'In progress' },
      { title: 'Get fit with steady training', area: 'Fitness and health', current: 0, target: 12, unit: 'weeks', status: 'Not started' },
      { title: 'Eat cleaner and hit protein', area: 'Fitness and health', current: 0, target: 90, unit: 'days at 100g+', status: 'Not started' },
    ],
  },
  {
    slug: 'roadmap',
    name: 'Career roadmap',
    icon: 'roadmap',
    blurb: 'The path from college to a ₹15L+ career, one stage at a time.',
    facts: [
      ['Paths considered', 'AI/ML engineer, GenAI engineer, full stack plus AI, research or M.Tech, founder, SaaS builder, freelancer'],
      ['Target', '₹15L+ package'],
    ],
    entity: 'stage',
    fields: [
      num('order', 'Order', { required: true }),
      text('title', 'Stage', { required: true }),
      sel('status', 'Status', ['Not started', 'In progress', 'Done']),
      area('note', 'Evidence or next step'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    numberKey: 'order',
    sort: { key: 'order', dir: 'asc' },
    kpis: [{ label: 'Stages done', calc: 'count', where: { status: 'Done' }, target: 10 }],
    seeds: [
      { order: 1, title: 'College', status: 'In progress' },
      { order: 2, title: 'Strong CS fundamentals', status: 'In progress' },
      { order: 3, title: 'DSA plus AI and GenAI', status: 'In progress' },
      { order: 4, title: 'Serious projects', status: 'Not started' },
      { order: 5, title: 'Portfolio and GitHub', status: 'Not started' },
      { order: 6, title: 'Paid GenAI internship', status: 'Not started' },
      { order: 7, title: 'Real engineering experience', status: 'Not started' },
      { order: 8, title: 'Income', status: 'Not started' },
      { order: 9, title: 'Higher value AI work, startup or SaaS', status: 'Not started' },
      { order: 10, title: '₹15L+ career potential', status: 'Not started' },
    ],
  },

  // ───────────────────────── Study
  {
    slug: 'academics',
    name: 'Academics',
    icon: 'academics',
    blurb: 'Second year, third semester. From about 7 CGPA to 8+.',
    facts: [
      ['Degree', 'B.Tech Computer Engineering'],
      ['College', 'Raisoni, Pune'],
      ['CET', '~86 percentile'],
      ['CGPA', '~7 now, 8+ target'],
    ],
    entity: 'item',
    fields: [
      text('title', 'Title', { required: true }),
      sel('kind', 'Type', ['Subject', 'Exam', 'Assignment', 'CGPA snapshot']),
      sel('status', 'Status', ['Not started', 'In progress', 'Revised', 'Done'], { showWhen: { kind: ['Subject', 'Exam', 'Assignment'] } }),
      num('cgpa', 'CGPA', { showWhen: { kind: 'CGPA snapshot' }, required: true }),
      date('date', 'Date', { showWhen: { kind: ['Exam', 'Assignment', 'CGPA snapshot'] } }),
      area('note', 'Notes'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'kind',
    chips: ['kind', 'cgpa', 'date'],
    metric: { key: 'cgpa', label: 'CGPA over time', target: 8, where: { kind: 'CGPA snapshot' } },
    kpis: [
      { label: 'CGPA', calc: 'latest', key: 'cgpa', target: 8 },
      { label: 'Open assignments', calc: 'count', where: { kind: 'Assignment', status: { not: ['Done'] } } },
    ],
    seeds: [
      { kind: 'CGPA snapshot', title: 'Current CGPA', cgpa: 7 },
      { kind: 'Subject', title: 'Data Structures and Algorithms', status: 'In progress' },
      { kind: 'Subject', title: 'Computer Organization and Architecture', status: 'In progress' },
      { kind: 'Subject', title: 'Algorithms', status: 'In progress' },
      { kind: 'Subject', title: 'Core Computer Science', status: 'In progress' },
      { kind: 'Subject', title: 'Mathematics', status: 'In progress' },
      { kind: 'Subject', title: 'Machine Learning', status: 'In progress' },
      { kind: 'Subject', title: 'Generative AI', status: 'In progress' },
    ],
  },
  {
    slug: 'gate',
    name: 'GATE prep',
    icon: 'gate',
    blurb: 'Fundamentals first, then previous year questions.',
    facts: [
      ['Goal', 'Rank under 100'],
      ['When', 'Third year'],
      ['After', 'M.Tech at a top IIT'],
      ['Method', 'Understand first, solve previous year questions, skip pure memorising'],
    ],
    entity: 'topic',
    fields: [
      text('title', 'Topic', { required: true }),
      sel('status', 'Status', ['Not started', 'Learning', 'Practising', 'Revised', 'Done']),
      num('pyqs', 'Questions solved'),
      num('accuracy', 'Accuracy', { unit: '%' }),
      date('date', 'Last practised', { default: '' }),
      area('note', 'Weak spots'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'status',
    chips: ['pyqs', 'accuracy', 'date'],
    kpis: [
      { label: 'Questions solved', calc: 'sum', key: 'pyqs' },
      { label: 'Topics done', calc: 'count', where: { status: 'Done' }, target: 12 },
      { label: 'Average accuracy', calc: 'avg', key: 'accuracy', unit: '%' },
    ],
    seeds: [
      { title: 'Engineering Mathematics', status: 'Learning' },
      { title: 'Discrete Mathematics', status: 'Not started' },
      { title: 'Digital Logic', status: 'Not started' },
      { title: 'Computer Organization and Architecture', status: 'Learning' },
      { title: 'Programming and Data Structures', status: 'Learning' },
      { title: 'Algorithms', status: 'Learning' },
      { title: 'Theory of Computation', status: 'Not started' },
      { title: 'Compiler Design', status: 'Not started' },
      { title: 'Operating Systems', status: 'Not started' },
      { title: 'Databases', status: 'Not started' },
      { title: 'Computer Networks', status: 'Not started' },
      { title: 'General Aptitude', status: 'Not started' },
    ],
  },
  {
    slug: 'dsa',
    name: 'DSA tracker',
    icon: 'dsa',
    blurb: '150+ questions in three months. One or two a day beats a weekend sprint.',
    facts: [
      ['Goal', '150+ questions'],
      ['Pace', '1 to 2 a day'],
    ],
    entity: 'problem',
    fields: [
      text('title', 'Problem', { required: true }),
      sel('status', 'Result', ['Solved', 'Revisit', 'Stuck']),
      sel('topic', 'Topic', ['Arrays', 'Strings', 'Linked list', 'Stack and queue', 'Hashing', 'Binary search', 'Recursion', 'Trees', 'Graphs', 'Dynamic programming', 'Greedy', 'Heap', 'Math', 'Bit manipulation', 'Other']),
      sel('difficulty', 'Difficulty', ['Easy', 'Medium', 'Hard']),
      sel('platform', 'Platform', ['LeetCode', 'GeeksforGeeks', 'Codeforces', 'CodeChef', 'Other']),
      date(),
      num('minutes', 'Time taken', { unit: 'min' }),
      url('link', 'Link'),
      area('note', 'What I learned'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'status',
    links: ['link'],
    chips: ['topic', 'difficulty', 'platform', 'minutes', 'date'],
    metric: { agg: 'count', where: { status: 'Solved' }, label: 'Solved per day', type: 'bar' },
    kpis: [
      { label: 'Solved', calc: 'count', where: { status: 'Solved' }, target: 150 },
      { label: 'This week', calc: 'count', where: { status: 'Solved' }, period: '7d', target: 10 },
      { label: 'Today', calc: 'count', where: { status: 'Solved' }, period: 'today', target: 2 },
      { label: 'Revisit queue', calc: 'count', where: { status: 'Revisit' } },
    ],
    seeds: [],
  },
  {
    slug: 'skills',
    name: 'Skills matrix',
    icon: 'skills',
    blurb: 'Rate yourself honestly. Shipped means a project proves it.',
    facts: [['Scale', 'Unrated, exploring, working, strong, shipped']],
    entity: 'skill',
    fields: [
      text('title', 'Skill', { required: true }),
      sel('category', 'Category', ['Programming', 'Web', 'Data and ML', 'GenAI and LLM', 'Backend and tools']),
      sel('level', 'Level', ['Unrated', 'Exploring', 'Working', 'Strong', 'Shipped']),
      url('link', 'Proof link'),
      text('note', 'Note'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'level',
    groupBy: 'category',
    filterKey: 'level',
    links: ['link'],
    sort: { key: 'title', dir: 'asc' },
    kpis: [
      { label: 'Skills listed', calc: 'count' },
      { label: 'Shipped', calc: 'count', where: { level: 'Shipped' } },
      { label: 'Unrated', calc: 'count', where: { level: 'Unrated' }, lowerBetter: true, target: 0 },
    ],
    seeds: [
      ...['Python', 'C', 'JavaScript', 'SQL', 'Data Structures and Algorithms', 'Git', 'GitHub'].map((t) => ({ category: 'Programming', title: t, level: 'Unrated' })),
      ...['HTML', 'CSS', 'Tailwind CSS', 'MERN full stack'].map((t) => ({ category: 'Web', title: t, level: 'Unrated' })),
      ...['NumPy', 'Pandas', 'Scikit-learn', 'TensorFlow', 'Keras', 'PyTorch', 'OpenCV', 'Data science', 'Machine learning'].map((t) => ({ category: 'Data and ML', title: t, level: 'Unrated' })),
      ...['Large language models', 'Generative AI', 'RAG', 'LangChain', 'LlamaIndex', 'Hugging Face', 'Embedding models', 'Vector databases', 'ChromaDB', 'FAISS', 'Groq API', 'Gemini', 'Ollama', 'TinyLlama', 'nomic embed text'].map((t) => ({ category: 'GenAI and LLM', title: t, level: 'Unrated' })),
      ...['Supabase', 'APIs', 'Vercel', 'Miniconda and Conda'].map((t) => ({ category: 'Backend and tools', title: t, level: 'Unrated' })),
    ],
  },

  // ───────────────────────── Career
  {
    slug: 'projects',
    name: 'Projects and portfolio',
    icon: 'projects',
    blurb: 'GitHub and shipped projects are the proof. Build things that solve real problems.',
    facts: [
      ['Rule', 'One project in Building at a time'],
      ['Aim', 'Employable without relying on the college brand'],
    ],
    entity: 'project',
    fields: [
      text('title', 'Project', { required: true }),
      sel('type', 'Type', ['RAG app', 'AI agent', 'Full stack', 'SaaS', 'Hackathon', 'Developer tool', 'Automation', 'Portfolio site']),
      sel('status', 'Status', ['Idea', 'Building', 'Deployed', 'Paused', 'Dropped']),
      text('stack', 'Stack', { placeholder: 'Next.js, Supabase, Groq' }),
      url('repo', 'GitHub link'),
      url('live', 'Live link'),
      num('users', 'Real users'),
      area('note', 'Problem it solves'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'status',
    links: ['repo', 'live'],
    chips: ['type', 'stack', 'users'],
    kpis: [
      { label: 'Building now', calc: 'count', where: { status: 'Building' }, lowerBetter: true, target: 1 },
      { label: 'Deployed', calc: 'count', where: { status: 'Deployed' }, target: 2 },
      { label: 'Real users', calc: 'sum', key: 'users' },
    ],
    seeds: [
      { title: 'Flagship GenAI project', type: 'RAG app', status: 'Idea', note: 'One deployed RAG or agent product with real users, evals and a clean README. This is the internship ticket.' },
      { title: 'Personal portfolio website', type: 'Portfolio site', status: 'Building', note: 'Home for the projects, GitHub and the UGC clips.' },
    ],
  },
  {
    slug: 'internships',
    name: 'Internship pipeline',
    icon: 'internships',
    blurb: 'Paid GenAI and AI internships. Track every application and follow up.',
    facts: [
      ['Looking at', 'Wellfound, Indian startups, remote, Pune, Bangalore, Hyderabad, Mumbai'],
      ['Cares about', 'Real work, mentorship, stipend, resume value'],
    ],
    entity: 'application',
    fields: [
      text('company', 'Company', { required: true }),
      text('role', 'Role'),
      sel('status', 'Status', ['Saved', 'Applied', 'Follow up', 'Interview', 'Offer', 'Rejected', 'Ghosted']),
      sel('source', 'Source', ['Wellfound', 'LinkedIn', 'Company site', 'Referral', 'Cold email', 'Other']),
      sel('location', 'Location', ['Remote', 'Pune', 'Bangalore', 'Hyderabad', 'Mumbai', 'Other']),
      num('stipend', 'Stipend per month', { prefix: '₹' }),
      date('date', 'Applied on'),
      date('next', 'Next step on', { default: '' }),
      url('link', 'Link'),
      area('note', 'Notes'),
    ],
    titleFn: (d) => `${d.role || 'Internship'} at ${d.company || 'Unknown'}`,
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'status',
    links: ['link'],
    chips: ['source', 'location', 'stipend', 'next'],
    kpis: [
      { label: 'Applied this week', calc: 'count', where: { status: { not: ['Saved'] } }, period: '7d', target: 10 },
      { label: 'Interviews', calc: 'count', where: { status: 'Interview' } },
      { label: 'Offers', calc: 'count', where: { status: 'Offer' }, target: 1 },
      { label: 'Tracked', calc: 'count' },
    ],
    seeds: [],
  },
  {
    slug: 'hackathons',
    name: 'Hackathons and clubs',
    icon: 'hackathons',
    blurb: 'Competitions, technical clubs and student coordinator roles.',
    facts: [
      ['Discussed', 'NexBuildOn Hack 2026'],
      ['Also', 'AI coding clubs, technical clubs, student organizations'],
    ],
    entity: 'item',
    fields: [
      text('title', 'Name', { required: true }),
      sel('kind', 'Type', ['Hackathon', 'Club', 'Coordinator role', 'Competition']),
      sel('status', 'Status', ['Exploring', 'Applied', 'Selected', 'Participating', 'Completed', 'Rejected']),
      date('date', 'Date', { default: '' }),
      url('link', 'Link'),
      area('note', 'Result or notes'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'kind',
    links: ['link'],
    chips: ['kind', 'date'],
    kpis: [
      { label: 'Active', calc: 'count', where: { status: ['Applied', 'Selected', 'Participating'] } },
      { label: 'Completed', calc: 'count', where: { status: 'Completed' } },
    ],
    seeds: [
      { title: 'NexBuildOn Hack 2026', kind: 'Hackathon', status: 'Exploring' },
      { title: 'AI coding club', kind: 'Club', status: 'Exploring' },
      { title: 'Student organizations', kind: 'Club', status: 'Selected', note: 'Selected for several after multiple interviews.' },
    ],
  },

  // ───────────────────────── Money
  {
    slug: 'money',
    name: 'Money tracker',
    icon: 'money',
    blurb: 'Every rupee earned and spent. The goal is ₹6k to ₹10k+ a month.',
    facts: [
      ['Goal', '₹6k to ₹10k+ per month'],
      ['Streams', 'Freelancing, digital products, SaaS'],
    ],
    entity: 'entry',
    fields: [
      date(),
      sel('type', 'Type', ['Income', 'Expense']),
      num('amount', 'Amount', { prefix: '₹', required: true }),
      sel('source', 'Source or category', ['Freelance', 'Digital product', 'Internship stipend', 'Tools and subscriptions', 'Ad spend', 'Food and health', 'Other']),
      text('note', 'Note'),
    ],
    titleFn: (d) => `${d.type} ${inr(d.amount)}${d.source ? ' from ' + d.source : ''}`,
    subKey: 'note',
    filterKey: 'type',
    chips: ['date'],
    kpis: [
      { label: 'Income this month', calc: 'sum', key: 'amount', where: { type: 'Income' }, period: 'month', prefix: '₹', target: 6000 },
      { label: 'Spend this month', calc: 'sum', key: 'amount', where: { type: 'Expense' }, period: 'month', prefix: '₹' },
      { label: 'Income all time', calc: 'sum', key: 'amount', where: { type: 'Income' }, prefix: '₹' },
    ],
    seeds: [],
  },
  {
    slug: 'clients',
    name: 'Freelance clients',
    icon: 'clients',
    blurb: 'Leads for AI UGC, ads, automation and small business marketing.',
    facts: [['Services', 'AI UGC videos, AI ads, AI automation, SMB marketing, Google Business Profile, influencer marketing, content']],
    entity: 'lead',
    fields: [
      text('title', 'Business or person', { required: true }),
      sel('service', 'Service', ['AI UGC video', 'AI ad', 'AI automation', 'SMB marketing', 'Google Business Profile', 'Influencer marketing', 'Content']),
      sel('stage', 'Stage', ['Lead', 'Contacted', 'Replied', 'Call booked', 'Proposal', 'Won', 'Lost']),
      num('value', 'Deal value', { prefix: '₹' }),
      date('next', 'Next action on', { default: '' }),
      text('contact', 'Contact'),
      area('note', 'Notes'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'stage',
    filterKey: 'stage',
    chips: ['service', 'value', 'next', 'contact'],
    kpis: [
      { label: 'Open leads', calc: 'count', where: { stage: OPEN_STAGES } },
      { label: 'Won', calc: 'count', where: { stage: 'Won' } },
      { label: 'Pipeline value', calc: 'sum', key: 'value', where: { stage: OPEN_STAGES }, prefix: '₹' },
    ],
    seeds: [],
  },
  {
    slug: 'ugc',
    name: 'AI UGC ads',
    icon: 'ugc',
    blurb: 'About 5 strong clips across categories. They should look like real commercial content, not obviously synthetic.',
    facts: [
      ['Portfolio goal', '5 strong clips'],
      ['Formats', '10 second segments, 30 second scripts, Hinglish, face pacing'],
      ['Avoid', 'Generic, repetitive AI ad look'],
    ],
    entity: 'clip',
    fields: [
      text('title', 'Clip', { required: true }),
      sel('category', 'Category', ['Skincare', "Men's skincare", 'SaaS', 'AI product', 'Consumer product', 'Small business']),
      sel('stage', 'Stage', ['Script', 'Generating', 'Editing', 'Ready', 'Sent to client', 'Rejected']),
      sel('length', 'Length', ['10 seconds', '30 seconds']),
      sel('language', 'Language', ['English', 'Hinglish', 'Hindi']),
      num('quality', 'Quality out of 5'),
      text('tool', 'Tools used'),
      url('link', 'Clip link'),
      area('note', 'Hook and script notes'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'stage',
    filterKey: 'stage',
    links: ['link'],
    chips: ['category', 'length', 'language', 'quality'],
    kpis: [
      { label: 'Ready clips', calc: 'count', where: { stage: ['Ready', 'Sent to client'] }, target: 5 },
      { label: 'In progress', calc: 'count', where: { stage: ['Script', 'Generating', 'Editing'] } },
    ],
    seeds: [
      { title: 'Skincare product ad', category: 'Skincare', stage: 'Script', length: '30 seconds', language: 'Hinglish' },
      { title: "Men's skincare ad", category: "Men's skincare", stage: 'Script', length: '30 seconds', language: 'Hinglish' },
      { title: 'SaaS product ad', category: 'SaaS', stage: 'Script', length: '30 seconds', language: 'English' },
      { title: 'AI product ad', category: 'AI product', stage: 'Script', length: '10 seconds', language: 'English' },
      { title: 'Local business ad', category: 'Small business', stage: 'Script', length: '30 seconds', language: 'Hinglish' },
    ],
  },
  {
    slug: 'products',
    name: 'Digital products',
    icon: 'products',
    blurb: 'Products and marketing experiments. Find out what actually converts.',
    facts: [
      ['Concept', '100+ verified internships for Indian students, ₹99 for 7 days'],
      ['Other', 'Internship Cheat Code field manual'],
      ['Stack', 'Razorpay, landing pages, Tailwind, Meta Ads, pixels, purchase events'],
    ],
    entity: 'item',
    fields: [
      text('title', 'Name', { required: true }),
      sel('kind', 'Type', ['Product', 'Experiment']),
      sel('stage', 'Stage', ['Idea', 'Building', 'Testing', 'Live', 'Killed']),
      num('price', 'Price', { prefix: '₹', showWhen: { kind: 'Product' } }),
      sel('channel', 'Channel', ['Meta Ads', 'Instagram organic', 'SEO', 'WhatsApp', 'Direct outreach', 'Other']),
      num('spend', 'Spend', { prefix: '₹' }),
      num('revenue', 'Revenue', { prefix: '₹' }),
      num('visitors', 'Visitors'),
      num('sales', 'Sales'),
      url('link', 'Link'),
      area('note', 'What I learned'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'stage',
    filterKey: 'kind',
    links: ['link'],
    chips: ['kind', 'channel', 'price', 'spend', 'revenue', 'visitors', 'sales'],
    kpis: [
      { label: 'Revenue', calc: 'sum', key: 'revenue', prefix: '₹' },
      { label: 'Spend', calc: 'sum', key: 'spend', prefix: '₹' },
      { label: 'Return on spend', calc: 'ratio', num: 'revenue', den: 'spend', suffix: 'x' },
      { label: 'Sales', calc: 'sum', key: 'sales' },
    ],
    seeds: [
      { title: 'Internship database for Indian students', kind: 'Product', stage: 'Building', price: 99, channel: 'Meta Ads', note: 'Company, role, direct link, location, stipend, eligibility, skills and last verified date.' },
      { title: 'Internship Cheat Code field manual', kind: 'Product', stage: 'Idea' },
      { title: 'Meta Ads and pixel test', kind: 'Experiment', stage: 'Idea', channel: 'Meta Ads', note: 'Check that purchase events fire, then measure what converts.' },
    ],
  },
  {
    slug: 'ideas',
    name: 'SaaS and startup ideas',
    icon: 'ideas',
    blurb: 'Park ideas here. An idea moves forward only after a customer conversation.',
    facts: [['Rule', 'No new build until the current one ships']],
    entity: 'idea',
    fields: [
      text('title', 'Idea', { required: true }),
      sel('category', 'Category', ['Small business', 'AI', 'Content', 'Career and education', 'Developer tool']),
      sel('stage', 'Stage', ['Raw', 'Validating', 'Building', 'Parked', 'Dead']),
      num('convos', 'Customer conversations'),
      text('payer', 'Who pays'),
      area('note', 'Problem and angle'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'stage',
    filterKey: 'stage',
    chips: ['category', 'payer', 'convos'],
    kpis: [
      { label: 'Building', calc: 'count', where: { stage: 'Building' }, lowerBetter: true, target: 1 },
      { label: 'Customer conversations', calc: 'sum', key: 'convos' },
      { label: 'Ideas', calc: 'count' },
    ],
    seeds: [
      { title: 'WhatsApp ordering for small shops', category: 'Small business', stage: 'Parked' },
      { title: 'SMB CRM', category: 'Small business', stage: 'Parked' },
      { title: 'Loyalty system for local stores', category: 'Small business', stage: 'Parked' },
      { title: 'Google QR and review system', category: 'Small business', stage: 'Parked' },
      { title: 'AI UGC agency', category: 'AI', stage: 'Raw' },
      { title: 'AI automation for small teams', category: 'AI', stage: 'Raw' },
      { title: 'GenAI developer tools', category: 'Developer tool', stage: 'Raw' },
      { title: 'Regularly updated internship database', category: 'Career and education', stage: 'Validating' },
    ],
  },
  {
    slug: 'investing',
    name: 'Investing and trading',
    icon: 'investing',
    blurb: 'Understanding money, markets, risk and automation.',
    facts: [
      ['Explored', 'ETFs (Nifty 500, Nifty Next 50, small cap), crypto, Solana'],
      ['Also', 'Binance APIs, trading automation, scalping, poker bankroll management'],
    ],
    entity: 'entry',
    fields: [
      date(),
      sel('kind', 'Type', ['Investment', 'Trade', 'Learning note']),
      text('title', 'Instrument or topic', { required: true }),
      sel('action', 'Action', ['Buy', 'SIP', 'Sell', 'Note'], { showWhen: { kind: ['Investment', 'Trade'] } }),
      num('amount', 'Amount', { prefix: '₹', showWhen: { kind: ['Investment', 'Trade'] } }),
      area('note', 'Notes or lesson'),
    ],
    titleKey: 'title',
    subKey: 'note',
    filterKey: 'kind',
    chips: ['kind', 'action', 'amount', 'date'],
    kpis: [
      { label: 'Put in', calc: 'sum', key: 'amount', where: { action: ['Buy', 'SIP'] }, prefix: '₹' },
      { label: 'Taken out', calc: 'sum', key: 'amount', where: { action: 'Sell' }, prefix: '₹' },
      { label: 'Notes', calc: 'count', where: { kind: 'Learning note' } },
    ],
    seeds: [],
  },

  // ───────────────────────── Body and mind
  {
    slug: 'fitness',
    name: 'Fitness and body',
    icon: 'fitness',
    blurb: 'From skinny fat to lean, muscular and athletic.',
    facts: [
      ['Height', '~6 ft'],
      ['Weight', '~64 to 65 kg'],
      ['Goal', 'Lean, muscular, athletic'],
    ],
    entity: 'entry',
    fields: [
      date(),
      sel('kind', 'Type', ['Weight', 'Workout', 'Measurement']),
      num('weight', 'Weight', { unit: 'kg', showWhen: { kind: 'Weight' }, required: true }),
      text('title', 'Session or measurement', { showWhen: { kind: ['Workout', 'Measurement'] }, required: true, placeholder: 'Push day, waist' }),
      num('minutes', 'Duration', { unit: 'min', showWhen: { kind: 'Workout' } }),
      num('value', 'Value', { unit: 'cm', showWhen: { kind: 'Measurement' } }),
      area('note', 'Notes'),
    ],
    titleFn: (d) => (d.kind === 'Weight' ? `Weight ${d.weight} kg` : d.title || d.kind),
    subKey: 'note',
    filterKey: 'kind',
    chips: ['kind', 'minutes', 'value', 'date'],
    metric: { key: 'weight', label: 'Body weight (kg)', where: { kind: 'Weight' } },
    kpis: [
      { label: 'Weight', calc: 'latest', key: 'weight', unit: 'kg' },
      { label: 'Workouts this week', calc: 'count', where: { kind: 'Workout' }, period: '7d', target: 4 },
    ],
    seeds: [{ kind: 'Weight', weight: 64.5 }],
  },
  {
    slug: 'nutrition',
    name: 'Nutrition',
    icon: 'nutrition',
    blurb: 'Practical, affordable food. 100 to 120 g of protein a day without expensive supplements.',
    facts: [
      ['Protein target', '100 to 120 g a day'],
      ['Staples', 'Chicken, eggs, milk, rice, roti, chicken curry, biryani, tea'],
    ],
    entity: 'meal',
    fields: [
      date(),
      sel('meal', 'Meal', ['Breakfast', 'Lunch', 'Snack', 'Dinner']),
      text('food', 'What you ate', { required: true, placeholder: '3 eggs, 2 rotis, chicken curry' }),
      num('protein', 'Protein', { unit: 'g' }),
      num('calories', 'Calories', { unit: 'kcal' }),
      text('note', 'Note'),
    ],
    titleKey: 'food',
    subKey: 'note',
    filterKey: 'meal',
    chips: ['meal', 'protein', 'calories', 'date'],
    metric: { key: 'protein', agg: 'sum', label: 'Protein per day (g)', target: 110, type: 'bar' },
    kpis: [
      { label: 'Protein today', calc: 'sum', key: 'protein', period: 'today', unit: 'g', target: 110 },
      { label: 'Calories today', calc: 'sum', key: 'calories', period: 'today', unit: 'kcal' },
      { label: 'Meals today', calc: 'count', period: 'today' },
    ],
    seeds: [],
  },
  {
    slug: 'appearance',
    name: 'Appearance and grooming',
    icon: 'appearance',
    blurb: 'Skin, hair, grooming and posture as small routines you actually repeat.',
    facts: [['Covers', 'Physique, hair, grooming, skin, posture, style']],
    entity: 'routine',
    recurring: { freqKey: 'frequency', lastKey: 'lastDone' },
    fields: [
      text('title', 'Routine', { required: true }),
      sel('category', 'Category', ['Skin', 'Hair', 'Grooming', 'Posture', 'Style']),
      sel('frequency', 'How often', ['Daily', 'Weekly', 'Monthly']),
      date('lastDone', 'Last done', { default: '' }),
      area('note', 'Notes'),
    ],
    titleKey: 'title',
    subKey: 'note',
    filterKey: 'category',
    chips: ['category', 'frequency'],
    kpis: [
      { label: 'Due now', calc: 'due', lowerBetter: true, target: 0 },
      { label: 'Routines', calc: 'count' },
    ],
    seeds: [
      { title: 'Skincare routine', category: 'Skin', frequency: 'Daily' },
      { title: 'Sunscreen before going out', category: 'Skin', frequency: 'Daily' },
      { title: 'Hair care', category: 'Hair', frequency: 'Weekly' },
      { title: 'Posture check while coding', category: 'Posture', frequency: 'Daily' },
      { title: 'Haircut and grooming', category: 'Grooming', frequency: 'Monthly' },
    ],
  },
  {
    slug: 'sleep',
    name: 'Sleep and discipline',
    icon: 'sleep',
    blurb: 'The cheapest fix in the whole dashboard. Bed before midnight, up by 6.',
    facts: [
      ['Now', 'Sleep 12 to 1 AM, wake 9 to 10 AM'],
      ['Target', 'Bed before midnight, wake 5 to 6 AM'],
    ],
    entity: 'night',
    beforeSave: 'sleep',
    fields: [
      date(),
      time('bed', 'Went to bed', { required: true }),
      time('wake', 'Woke up', { required: true }),
      num('quality', 'Quality out of 5'),
      text('note', 'Note'),
      { key: 'hours', label: 'Slept', type: 'number', unit: 'h', computed: true },
    ],
    titleFn: (d) => `${d.bed} to ${d.wake}`,
    subKey: 'note',
    chips: ['hours', 'quality', 'date'],
    flags: [
      { key: 'earlyBed', label: 'Bed before midnight' },
      { key: 'earlyWake', label: 'Up by 6:30' },
    ],
    metric: { key: 'hours', label: 'Hours slept', type: 'bar' },
    kpis: [
      { label: 'Last night', calc: 'latest', key: 'hours', unit: 'h' },
      { label: 'Bed before midnight, 7 days', calc: 'count', where: { earlyBed: true }, period: '7d', target: 7 },
      { label: 'Up by 6:30, 7 days', calc: 'count', where: { earlyWake: true }, period: '7d', target: 7 },
    ],
    seeds: [],
  },
  {
    slug: 'screen',
    name: 'Screen time',
    icon: 'screen',
    blurb: 'Stop feeding the reels. Log the number, watch it fall.',
    facts: [['Problem', 'Instagram and reels eating large parts of the day']],
    entity: 'day',
    fields: [
      date(),
      num('total', 'Total screen time', { unit: 'h', required: true }),
      num('reels', 'Instagram and reels', { unit: 'h', required: true }),
      text('note', 'Note'),
    ],
    titleFn: (d) => `Reels ${d.reels ?? 0} h of ${d.total ?? 0} h`,
    subKey: 'note',
    chips: ['date'],
    metric: { key: 'reels', label: 'Reels hours per day', target: 1, lowerBetter: true, type: 'bar' },
    kpis: [
      { label: 'Reels today', calc: 'sum', key: 'reels', period: 'today', unit: 'h', lowerBetter: true, target: 1 },
      { label: 'Reels average, 7 days', calc: 'avg', key: 'reels', period: '7d', unit: 'h', lowerBetter: true, target: 1 },
      { label: 'Screen average, 7 days', calc: 'avg', key: 'total', period: '7d', unit: 'h' },
    ],
    seeds: [],
  },
  {
    slug: 'chess',
    name: 'Chess',
    icon: 'chess',
    blurb: 'About 1500 by 3 March, your birthday. Chess trains strategy and focus.',
    facts: [
      ['Goal', '~1500 rating'],
      ['By', '3 March 2027'],
    ],
    entity: 'rating',
    fields: [
      date(),
      num('rating', 'Rating', { required: true }),
      sel('platform', 'Platform', ['Chess.com', 'Lichess', 'Other']),
      sel('format', 'Format', ['Rapid', 'Blitz', 'Bullet', 'Classical']),
      num('games', 'Games played'),
      area('note', 'Lesson from losses'),
    ],
    titleFn: (d) => `Rating ${d.rating}`,
    subKey: 'note',
    chips: ['platform', 'format', 'games', 'date'],
    metric: { key: 'rating', label: 'Rating over time', target: 1500, deadline: '2027-03-03' },
    kpis: [
      { label: 'Rating', calc: 'latest', key: 'rating', target: 1500 },
      { label: 'Games logged', calc: 'sum', key: 'games' },
    ],
    seeds: [],
  },

  // ───────────────────────── Daily and reach
  {
    slug: 'planner',
    name: 'Daily planner and review',
    icon: 'planner',
    blurb: 'Plan the day, then review it at 10 to 11 PM.',
    facts: [
      ['Review time', '10 to 11 PM'],
      ['Aim', 'Track, plan, review, stay accountable'],
    ],
    entity: 'entry',
    fields: [
      sel('kind', 'Type', ['Task', 'Review']),
      text('title', 'Task', { required: true, showWhen: { kind: 'Task' } }),
      sel('area', 'Area', AREAS, { showWhen: { kind: 'Task' } }),
      sel('priority', 'Priority', ['Top 3', 'Normal'], { showWhen: { kind: 'Task' } }),
      check('done', 'Done', { showWhen: { kind: 'Task' } }),
      date(),
      num('score', 'How was the day, 1 to 10', { showWhen: { kind: 'Review' }, required: true }),
      area('wins', 'What went well', { showWhen: { kind: 'Review' } }),
      area('misses', 'What slipped', { showWhen: { kind: 'Review' } }),
      area('tomorrow', 'Top 3 for tomorrow', { showWhen: { kind: 'Review' } }),
    ],
    titleFn: (d) => (d.kind === 'Review' ? `Review for ${d.date}` : d.title),
    subFn: (d) => (d.kind === 'Review' ? [d.wins && `Went well: ${d.wins}`, d.misses && `Slipped: ${d.misses}`, d.tomorrow && `Tomorrow: ${d.tomorrow}`].filter(Boolean).join('  ') : ''),
    doneKey: 'done',
    filterKey: 'kind',
    chips: ['area', 'priority', 'score', 'date'],
    metric: { key: 'score', label: 'Day score', where: { kind: 'Review' } },
    kpis: [
      { label: 'Tasks done today', calc: 'count', where: { kind: 'Task', done: true }, period: 'today' },
      { label: 'Tasks open today', calc: 'count', where: { kind: 'Task', done: false }, period: 'today' },
      { label: 'Last review score', calc: 'latest', key: 'score', where: { kind: 'Review' } },
    ],
    seeds: [],
  },
  {
    slug: 'social',
    name: 'Social and content',
    icon: 'social',
    blurb: 'Use platforms as tools for content, leads and networking, not just as a viewer.',
    facts: [
      ['Explored', 'Instagram reels, meme pages, fan pages, AI content, UGC'],
      ['Aim', 'Audience, leads and product sales'],
    ],
    entity: 'post',
    fields: [
      text('title', 'Post or idea', { required: true }),
      sel('platform', 'Platform', ['Instagram reels', 'Meme page', 'Fan page', 'LinkedIn', 'X', 'YouTube']),
      sel('goal', 'Goal', ['Audience', 'Leads', 'Sales', 'Networking']),
      sel('status', 'Status', ['Idea', 'Scripted', 'Posted', 'Analysed']),
      date(),
      num('views', 'Views'),
      num('followers', 'Followers gained'),
      url('link', 'Link'),
      area('note', 'What worked'),
    ],
    titleKey: 'title',
    subKey: 'note',
    statusKey: 'status',
    filterKey: 'status',
    links: ['link'],
    chips: ['platform', 'goal', 'views', 'followers'],
    kpis: [
      { label: 'Posted', calc: 'count', where: { status: ['Posted', 'Analysed'] } },
      { label: 'Total views', calc: 'sum', key: 'views' },
      { label: 'Followers gained', calc: 'sum', key: 'followers' },
    ],
    seeds: [],
  },
];

export const BY_SLUG = Object.fromEntries(MODULES.map((m) => [m.slug, m]));
export const DOB = '2008-03-03';
